#!/usr/bin/env node
var fs = require('fs'),
	path = require('path'),
	_  = require('underscore');

var compiler = require('./dist/compiler.js');

// Split the args into compiler flags and source filenames
var groupedArgs = _.groupBy(process.argv.slice(2), function(arg) {
	return (arg.trim()[0] === '-') ? 'flags' : 'filenames';
});

// Process flag arguments
var flags = _.groupBy(groupedArgs.flags, function (flag) {
	// PRE: Flag starts with a -
	return flag.substr(1);
});

// Process source file arguments
var mainFilename = _.first(groupedArgs.filenames);
var headerFilenames = _.tail(groupedArgs.filenames);
var outputFilename = path.basename(mainFilename, '.wacc') + '.s';
console.log(flags);
compiler.compile(mainFilename, headerFilenames, outputFilename, flags.barebones);
