#!/usr/bin/env node
var fs = require('fs'),
	path = require('path'),
	_  = require('underscore');

var compiler = require('./dist/compiler.js');

// Split the args into compiler flags and source filenames
var groupedArgs = _.groupBy(process.argv.slice(2), function(arg) {
	return (arg.trim()[0] === '-') ? 'flags' : 'filenames';
});

// Process flag arguments
var flags = {};
// Fill in flags by going through array;
_.forEach(groupedArgs.flags, function(flag) {
	// PRE: flags start with -
	flags[flag.substr(1)] = true;
})

// Process source file arguments
var mainFilename = _.first(groupedArgs.filenames);
var headerFilenames = _.tail(groupedArgs.filenames);
var outputFilename = path.basename(mainFilename, '.wacc') + '.s';
compiler.compile(mainFilename, headerFilenames, outputFilename);
