#!/usr/bin/env node
var fs = require('fs'),
	path = require('path');
var compiler = require('./dist/compiler.js');

var inputFile = process.argv[2];
var	outputFile;

if (process.argv.length === 3) {
	outputFile = path.basename(inputFile, '.wacc') + '.s';
} else {
	outputFile = process.argv[3].split(path.extname(outputFile))[0] + '.s';
}

compiler.compile(inputFile, outputFile);